FROM ubuntu:22.04

RUN dpkg --add-architecture i386 && \
    apt update && \
    apt install -y \
    ca-certificates \
    lib32gcc-s1 \
    lib32stdc++6 \
    libcurl4 \
    libcurl4:i386 \
    libsdl2-2.0-0 \
    libsdl2-2.0-0:i386 \
    libopenal1 \
    libopenal1:i386 \
    libgl1 \
    libgl1:i386 && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /pz
