services:
  gamebot:
    build: .
    container_name: gamebot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/libvirt:/var/run/libvirt
      - /srv/scripts:/srv/scripts
#extra_hosts:
 #     - "host.docker.internal:host-gateway"
