services:
  7days2die:
    build: .
    container_name: 7days2die
    restart: unless-stopped
    working_dir: /7d
    command: bash -c "./startserver.sh -configfile=serverconfig.xml"
    ports:
      - "26900:26900/tcp"
      - "26900-26902:26900-26902/udp"
    volumes:
      - /srv/data/games/7days2die:/7d
